const fs = require("fs/promises");
const path = require("path");
const extractZip = require("extract-zip");

const {
  TMP_DIR,
  PUBLIC_GAME_HOST
} = require("../config");
const { spawnBuffered } = require("./commands");
const {
  createHttpError,
  coerceBoolean,
  coerceNullableString,
  normalizeRelativePath,
  nowIso,
  randomId
} = require("./utils");

const FIVEM_ARTIFACTS_URL = "https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/";
const CFX_SERVER_DATA_ZIP_URL =
  "https://github.com/citizenfx/cfx-server-data/archive/refs/heads/master.zip";
const PUBLIC_HOST_CACHE_TTL_MS = 10 * 60 * 1000;

const MANAGED_BLOCK_START = "# >>> ByteHost FiveM managed block";
const MANAGED_BLOCK_END = "# <<< ByteHost FiveM managed block";

let publicHostCache = {
  value: "",
  expiresAt: 0
};

function buildFiveMStartCommand(entryFile = "run.sh", configFile = "server.cfg") {
  const normalizedEntryFile = normalizeRelativePath(entryFile || "run.sh") || "run.sh";
  const normalizedConfigFile = normalizeRelativePath(configFile || "server.cfg") || "server.cfg";
  return `bash "${normalizedEntryFile}" +exec "${normalizedConfigFile}"`;
}

function normalizePublicHost(value) {
  const rawValue = coerceNullableString(value, "") || "";
  if (!rawValue) {
    return "";
  }

  return rawValue
    .replace(/^https?:\/\//i, "")
    .replace(/\/.*$/, "")
    .replace(/:\d+$/, "")
    .trim();
}

async function fetchWithTimeout(url, options = {}) {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), Number(options.timeoutMs || 10000));

  try {
    return await fetch(url, {
      ...options,
      signal: controller.signal
    });
  } catch (error) {
    if (error?.name === "AbortError") {
      throw createHttpError(504, `Przekroczono limit czasu podczas pobierania ${url}.`);
    }

    throw error;
  } finally {
    clearTimeout(timeoutId);
  }
}

async function fetchText(url, options = {}) {
  const response = await fetchWithTimeout(url, options);

  if (!response.ok) {
    throw createHttpError(502, `Nie udalo sie pobrac danych FiveM z ${url}.`);
  }

  return response.text();
}

async function fetchBuffer(url, options = {}) {
  const response = await fetchWithTimeout(url, options);

  if (!response.ok) {
    throw createHttpError(502, `Nie udalo sie pobrac pliku z ${url}.`);
  }

  return Buffer.from(await response.arrayBuffer());
}

async function ensureDirectory(targetPath) {
  await fs.mkdir(targetPath, { recursive: true });
}

async function readUtf8IfExists(targetPath) {
  try {
    return await fs.readFile(targetPath, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") {
      return null;
    }

    throw error;
  }
}

async function pathExists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch (_error) {
    return false;
  }
}

function escapeCfgValue(value) {
  return String(value || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildManagedFiveMConfig(bot) {
  const port = Number(bot.public_port || 30120);
  const serverName = coerceNullableString(bot.name, "ByteHost FiveM Server");
  const projectName = coerceNullableString(bot.fivem_project_name, serverName);
  const projectDescription = coerceNullableString(
    bot.description,
    "Serwer FiveM hostowany przez ByteHost."
  );
  const tags = coerceNullableString(bot.fivem_tags, "default");
  const locale = coerceNullableString(bot.fivem_locale, "pl-PL");
  const maxClients = Math.min(128, Math.max(1, Number(bot.fivem_max_clients || 48)));
  const licenseKey = coerceNullableString(bot.fivem_license_key, "changeme");
  const onesyncValue = coerceBoolean(bot.fivem_onesync_enabled, true) ? "on" : "off";

  return [
    MANAGED_BLOCK_START,
    `# Generated by ByteHost at ${nowIso()}`,
    `endpoint_add_tcp "0.0.0.0:${port}"`,
    `endpoint_add_udp "0.0.0.0:${port}"`,
    "",
    "ensure mapmanager",
    "ensure chat",
    "ensure spawnmanager",
    "ensure sessionmanager",
    "ensure basic-gamemode",
    "ensure hardcap",
    "ensure rconlog",
    "",
    "sv_scriptHookAllowed 0",
    `sets tags "${escapeCfgValue(tags)}"`,
    `sets locale "${escapeCfgValue(locale)}"`,
    `sv_hostname "${escapeCfgValue(serverName)}"`,
    `sets sv_projectName "${escapeCfgValue(projectName)}"`,
    `sets sv_projectDesc "${escapeCfgValue(projectDescription)}"`,
    `set onesync ${onesyncValue}`,
    `sv_maxclients ${maxClients}`,
    'set steam_webApiKey ""',
    `sv_licenseKey "${escapeCfgValue(licenseKey)}"`,
    MANAGED_BLOCK_END,
    ""
  ].join("\n");
}

function mergeManagedFiveMConfig(existingContent, managedBlock) {
  const blockPattern = new RegExp(
    `${MANAGED_BLOCK_START.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${MANAGED_BLOCK_END.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*`,
    "m"
  );

  if (blockPattern.test(existingContent)) {
    return existingContent.replace(blockPattern, `${managedBlock}\n`);
  }

  if (!existingContent.trim()) {
    return `${managedBlock}\n`;
  }

  return `${managedBlock}\n${existingContent.trimStart()}`;
}

async function writeFiveMServerConfig(projectPath, bot) {
  const serverCfgPath = path.join(projectPath, "server.cfg");
  const currentContent = (await readUtf8IfExists(serverCfgPath)) || "";
  const nextContent = mergeManagedFiveMConfig(currentContent, buildManagedFiveMConfig(bot));
  await fs.writeFile(serverCfgPath, nextContent, "utf8");
  return serverCfgPath;
}

async function createFiveMReadme(projectPath) {
  const readmePath = path.join(projectPath, "README_BYTEHOST_FIVEM.txt");

  if (await pathExists(readmePath)) {
    return;
  }

  await fs.writeFile(
    readmePath,
    [
      "ByteHost przygotowal serwer FiveM na bazie oficjalnego artefaktu FXServer oraz cfx-server-data.",
      "",
      "Najwazniejsze rzeczy:",
      "1. Ustaw poprawny klucz `sv_licenseKey` w panelu zanim uruchomisz serwer publicznie.",
      "2. Wrzucaj resources/mods/pluginy do folderu resources/ przez File Manager.",
      "3. `server.cfg` ma blok zarzadzany przez ByteHost, ale mozesz dopisywac wlasne komendy ponizej.",
      "4. Port gry musi byc przekierowany na routerze, jesli serwer ma byc publiczny.",
      ""
    ].join("\n"),
    "utf8"
  );
}

async function getExtractedRoot(directoryPath) {
  const entries = await fs.readdir(directoryPath, { withFileTypes: true });
  const visibleEntries = entries.filter((entry) => !entry.name.startsWith("."));

  if (visibleEntries.length === 1 && visibleEntries[0].isDirectory()) {
    return path.join(directoryPath, visibleEntries[0].name);
  }

  return directoryPath;
}

async function copyDirectoryContents(sourceDirectory, destinationDirectory) {
  await ensureDirectory(destinationDirectory);
  const entries = await fs.readdir(sourceDirectory, { withFileTypes: true });

  for (const entry of entries) {
    await fs.cp(path.join(sourceDirectory, entry.name), path.join(destinationDirectory, entry.name), {
      recursive: true,
      force: true
    });
  }
}

function parseFiveMArtifactInfo(listingHtml) {
  const recommendedMatch = listingHtml.match(
    /href\s*=\s*"\.\/([^"/]+)\/fx\.tar\.xz"[^>]*>\s*LATEST RECOMMENDED\s*\((\d+)\)/i
  );

  if (!recommendedMatch) {
    throw createHttpError(502, "Nie udalo sie odczytac najnowszego rekomendowanego artefaktu FiveM.");
  }

  const artifactPath = recommendedMatch[1];
  const build = recommendedMatch[2];

  return {
    build,
    artifact_path: artifactPath,
    url: `${FIVEM_ARTIFACTS_URL}${artifactPath}/fx.tar.xz`
  };
}

async function getLatestRecommendedFiveMArtifact() {
  const listingHtml = await fetchText(FIVEM_ARTIFACTS_URL, {
    timeoutMs: 15000
  });

  return parseFiveMArtifactInfo(listingHtml);
}

async function downloadAndExtractTar(url, destinationDirectory) {
  const archivePath = path.join(TMP_DIR, `fivem-${randomId()}.tar.xz`);

  try {
    const buffer = await fetchBuffer(url, { timeoutMs: 90000 });
    await fs.writeFile(archivePath, buffer);

    try {
      await spawnBuffered("tar", ["-xf", archivePath, "-C", destinationDirectory], {
        cwd: destinationDirectory,
        timeoutMs: 120000
      });
    } catch (error) {
      if (error.code === "ENOENT") {
        throw createHttpError(
          500,
          "FiveM wymaga polecenia `tar` oraz pakietu `xz-utils` na serwerze Ubuntu."
        );
      }

      throw createHttpError(400, `Nie udalo sie rozpakowac artefaktu FiveM: ${error.message}`);
    }
  } finally {
    await fs.rm(archivePath, { force: true });
  }
}

async function downloadAndExtractZip(url, destinationDirectory) {
  const archivePath = path.join(TMP_DIR, `fivem-data-${randomId()}.zip`);

  try {
    const buffer = await fetchBuffer(url, { timeoutMs: 90000 });
    await fs.writeFile(archivePath, buffer);
    await extractZip(archivePath, {
      dir: destinationDirectory
    });
  } finally {
    await fs.rm(archivePath, { force: true });
  }
}

async function ensureFiveMRuntime(projectPath) {
  await ensureDirectory(projectPath);
  const artifact = await getLatestRecommendedFiveMArtifact();
  await downloadAndExtractTar(artifact.url, projectPath);

  const runScriptPath = path.join(projectPath, "run.sh");
  if (await pathExists(runScriptPath)) {
    await fs.chmod(runScriptPath, 0o755).catch(() => {});
  }

  return artifact;
}

async function ensureFiveMServerData(projectPath) {
  const resourcesDirectory = path.join(projectPath, "resources");
  if (await pathExists(resourcesDirectory)) {
    return;
  }

  const extractDirectory = path.join(TMP_DIR, `cfx-server-data-${randomId()}`);

  try {
    await ensureDirectory(extractDirectory);
    await downloadAndExtractZip(CFX_SERVER_DATA_ZIP_URL, extractDirectory);
    const extractedRoot = await getExtractedRoot(extractDirectory);
    await copyDirectoryContents(extractedRoot, projectPath);
  } finally {
    await fs.rm(extractDirectory, { recursive: true, force: true });
  }
}

async function bootstrapFiveMWorkspace(projectPath, bot) {
  const artifact = await ensureFiveMRuntime(projectPath);
  await ensureFiveMServerData(projectPath);
  await ensureDirectory(path.join(projectPath, "resources", "[local]"));
  await ensureDirectory(path.join(projectPath, "resources", "[bytehost]"));
  await createFiveMReadme(projectPath);
  await writeFiveMServerConfig(projectPath, bot);

  return {
    fivem_artifact_build: artifact.build,
    entry_file: "run.sh"
  };
}

async function repairFiveMWorkspace(projectPath, bot) {
  const artifact = await ensureFiveMRuntime(projectPath);
  await ensureFiveMServerData(projectPath);
  await ensureDirectory(path.join(projectPath, "resources", "[local]"));
  await ensureDirectory(path.join(projectPath, "resources", "[bytehost]"));
  await createFiveMReadme(projectPath);
  await writeFiveMServerConfig(projectPath, bot);

  return {
    fivem_artifact_build: artifact.build,
    entry_file: "run.sh"
  };
}

async function detectPublicGameHost() {
  const configuredHost = normalizePublicHost(PUBLIC_GAME_HOST);
  if (configuredHost) {
    return configuredHost;
  }

  if (publicHostCache.value && publicHostCache.expiresAt > Date.now()) {
    return publicHostCache.value;
  }

  const providers = [
    {
      url: "https://api.ipify.org?format=json",
      parse: async (response) => {
        const payload = await response.json();
        return normalizePublicHost(payload?.ip || "");
      }
    },
    {
      url: "https://ifconfig.me/ip",
      parse: async (response) => normalizePublicHost(await response.text())
    },
    {
      url: "https://www.cloudflare.com/cdn-cgi/trace",
      parse: async (response) => {
        const payload = await response.text();
        const match = payload.match(/^ip=(.+)$/m);
        return normalizePublicHost(match?.[1] || "");
      }
    }
  ];

  for (const provider of providers) {
    try {
      const response = await fetchWithTimeout(provider.url, {
        timeoutMs: 5000
      });

      if (!response.ok) {
        continue;
      }

      const host = await provider.parse(response);
      if (host) {
        publicHostCache = {
          value: host,
          expiresAt: Date.now() + PUBLIC_HOST_CACHE_TTL_MS
        };
        return host;
      }
    } catch (_error) {
      continue;
    }
  }

  return "";
}

module.exports = {
  buildFiveMStartCommand,
  bootstrapFiveMWorkspace,
  detectPublicGameHost,
  getLatestRecommendedFiveMArtifact,
  normalizePublicHost,
  repairFiveMWorkspace,
  writeFiveMServerConfig
};
